# Generated by Django 5.2 on 2025-05-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_vk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
