# Generated by Django 5.2 on 2025-05-16 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_vk', '0002_medicalbranch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedicalBranch',
            new_name='Illness',
        ),
    ]
