# Generated by Django 5.2 on 2025-05-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_vk', '0003_rename_medicalbranch_illness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='specialization',
        ),
    ]
