# Generated by Django 5.2 on 2025-05-26 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_vk', '0005_alter_chatroom_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
    ]
