# Generated by Django 5.2 on 2025-06-07 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_vk', '0008_appointment_notes_doctorschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='illness',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auth_vk.doctor'),
        ),
    ]
