# Generated by Django 5.2 on 2025-06-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_vk', '0009_illness_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='treatable_illnesses',
        ),
        migrations.RemoveField(
            model_name='illness',
            name='doctor',
        ),
        migrations.AddField(
            model_name='illness',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='illnesses_doctor', to='auth_vk.doctor'),
        ),
    ]
