# Generated by Django 5.2 on 2025-06-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_vk', '0010_remove_doctor_treatable_illnesses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='clinics',
        ),
        migrations.AddField(
            model_name='user',
            name='clinics',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='auth_vk.clinic'),
        ),
    ]
