# Generated by Django 5.2 on 2025-06-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_vk', '0011_remove_doctor_clinics_user_clinics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
