# Generated by Django 5.2 on 2025-06-10 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_vk', '0012_alter_specialization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illness',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='illnesses_doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
