# Generated by Django 5.2 on 2025-06-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_vk', '0015_banner_alter_doctorschedule_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='news',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='news',
            name='published_at',
        ),
        migrations.AddField(
            model_name='news',
            name='file',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
