# Generated by Django 5.2 on 2025-06-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_vk', '0016_delete_banner_rename_content_news_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
