# Generated by Django 5.2 on 2025-06-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_vk', '0017_user_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
