# Generated by Django 5.2 on 2025-07-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_vk', '0019_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
