# Generated by Django 5.2 on 2025-07-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_vk', '0023_user_employee_id_alter_message_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MessageImage',
        ),
    ]
