# Generated by Django 5.2 on 2025-07-22 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_vk', '0026_alter_news_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AlterModelOptions(
            name='chatroom',
            options={'ordering': ['-last_message_at', '-created_at'], 'verbose_name': 'Chat Room', 'verbose_name_plural': 'Chat Rooms'},
        ),
        migrations.AlterModelOptions(
            name='clinic',
            options={'ordering': ['name'], 'verbose_name': 'Clinic', 'verbose_name_plural': 'Clinics'},
        ),
        migrations.AlterModelOptions(
            name='clinicimage',
            options={'verbose_name': 'Clinic Image', 'verbose_name_plural': 'Clinic Images'},
        ),
        migrations.AlterModelOptions(
            name='devicetoken',
            options={'verbose_name': 'Device Token', 'verbose_name_plural': 'Device Tokens'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Doctor (Legacy)', 'verbose_name_plural': 'Doctors (Legacy)'},
        ),
        migrations.AlterModelOptions(
            name='doctorschedule',
            options={'verbose_name': 'Doctor Schedule', 'verbose_name_plural': 'Doctor Schedules'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='feedbackrequest',
            options={'verbose_name': 'Feedback Request', 'verbose_name_plural': 'Feedback Requests'},
        ),
        migrations.AlterModelOptions(
            name='illness',
            options={'ordering': ['name'], 'verbose_name': 'Illness', 'verbose_name_plural': 'Illnesses'},
        ),
        migrations.AlterModelOptions(
            name='integrationsettings',
            options={'verbose_name': 'Integration Setting', 'verbose_name_plural': 'Integration Settings'},
        ),
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'verbose_name': 'Medical Record', 'verbose_name_plural': 'Medical Records'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='notificationlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification Log', 'verbose_name_plural': 'Notification Logs'},
        ),
        migrations.AlterModelOptions(
            name='notificationrecipient',
            options={'verbose_name': 'Notification Recipient', 'verbose_name_plural': 'Notification Recipients'},
        ),
        migrations.AlterModelOptions(
            name='onecsynclog',
            options={'verbose_name': '1C Sync Log', 'verbose_name_plural': '1C Sync Logs'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name': 'Promotion', 'verbose_name_plural': 'Promotions'},
        ),
        migrations.AlterModelOptions(
            name='recommendation',
            options={'verbose_name': 'Recommendation', 'verbose_name_plural': 'Recommendations'},
        ),
        migrations.AlterModelOptions(
            name='recommendationfile',
            options={'verbose_name': 'Recommendation File', 'verbose_name_plural': 'Recommendation Files'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name': 'Service Category', 'verbose_name_plural': 'Service Categories'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'Specialization', 'verbose_name_plural': 'Specializations'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth_vk.clinic', verbose_name='Clinic'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='External ID'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'user_type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_chats', to=settings.AUTH_USER_MODEL, verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='last_message_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Message At'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_chats', to=settings.AUTH_USER_MODEL, verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='uuid',
            field=models.CharField(max_length=100, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='clinicimage',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='auth_vk.clinic', verbose_name='Clinic'),
        ),
        migrations.AlterField(
            model_name='clinicimage',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='clinicimage',
            name='image',
            field=models.ImageField(upload_to='clinic_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='device_type',
            field=models.CharField(max_length=20, verbose_name='Device Type'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='token',
            field=models.CharField(max_length=255, verbose_name='Token'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='External ID'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='price_per_visit',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per Visit'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0, verbose_name='Years of Experience'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_schedules', to='auth_vk.clinic', verbose_name='Clinic'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL, verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='end_time',
            field=models.TimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='start_time',
            field=models.TimeField(verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='Weekday'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=255, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='new', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='illness',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='illness',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='illness',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='illnesses_doctor', to=settings.AUTH_USER_MODEL, verbose_name='Doctors'),
        ),
        migrations.AlterField(
            model_name='illness',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='illness',
            name='severity_level',
            field=models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('critical', 'Critical')], default='mild', max_length=20, verbose_name='Severity Level'),
        ),
        migrations.AlterField(
            model_name='illness',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='integrationsettings',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='integrationsettings',
            name='api_token',
            field=models.CharField(max_length=255, verbose_name='API Token'),
        ),
        migrations.AlterField(
            model_name='integrationsettings',
            name='api_url',
            field=models.URLField(verbose_name='API URL'),
        ),
        migrations.AlterField(
            model_name='integrationsettings',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_vk.appointment', verbose_name='Appointment'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='diagnosis',
            field=models.TextField(verbose_name='Diagnosis'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth_vk.doctor', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='External ID'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='recommendations',
            field=models.TextField(verbose_name='Recommendations'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='auth_vk.chatroom', verbose_name='Chat Room'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Is Read'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender'),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Read'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('appointment', 'Appointment'), ('message', 'Message'), ('system', 'System'), ('promo', 'Promotional')], max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='failed_deliveries',
            field=models.IntegerField(default=0, verbose_name='Failed Deliveries'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='filter_criteria',
            field=models.JSONField(blank=True, null=True, verbose_name='Filter Criteria'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('general', 'General'), ('appointment', 'Appointment'), ('health_tip', 'Health Tip'), ('emergency', 'Emergency'), ('promotion', 'Promotion')], default='general', max_length=50, verbose_name='Notification Type'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='recipient_count',
            field=models.IntegerField(default=0, verbose_name='Recipient Count'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scheduled For'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sent At'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='sent_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Sent By'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='successful_deliveries',
            field=models.IntegerField(default=0, verbose_name='Successful Deliveries'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='notificationrecipient',
            name='clicked',
            field=models.BooleanField(default=False, verbose_name='Clicked'),
        ),
        migrations.AlterField(
            model_name='notificationrecipient',
            name='clicked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Clicked At'),
        ),
        migrations.AlterField(
            model_name='notificationrecipient',
            name='delivered',
            field=models.BooleanField(default=False, verbose_name='Delivered'),
        ),
        migrations.AlterField(
            model_name='notificationrecipient',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delivery Time'),
        ),
        migrations.AlterField(
            model_name='notificationrecipient',
            name='device_token',
            field=models.CharField(blank=True, max_length=255, verbose_name='Device Token'),
        ),
        migrations.AlterField(
            model_name='notificationrecipient',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Error Message'),
        ),
        migrations.AlterField(
            model_name='notificationrecipient',
            name='notification_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='auth_vk.notificationlog', verbose_name='Notification Log'),
        ),
        migrations.AlterField(
            model_name='notificationrecipient',
            name='opened',
            field=models.BooleanField(default=False, verbose_name='Opened'),
        ),
        migrations.AlterField(
            model_name='notificationrecipient',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Opened At'),
        ),
        migrations.AlterField(
            model_name='notificationrecipient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='onecsynclog',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed At'),
        ),
        migrations.AlterField(
            model_name='onecsynclog',
            name='message',
            field=models.TextField(blank=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='onecsynclog',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Started At'),
        ),
        migrations.AlterField(
            model_name='onecsynclog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='onecsynclog',
            name='sync_type',
            field=models.CharField(max_length=50, verbose_name='Sync Type'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='promotion_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth_vk.doctor', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='recommendationfile',
            name='file',
            field=models.FileField(upload_to='recommendation_files/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='recommendationfile',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='auth_vk.recommendation', verbose_name='Recommendation'),
        ),
        migrations.AlterField(
            model_name='recommendationfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_vk.servicecategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.DurationField(verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='service',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='External ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='agreed_to_terms',
            field=models.BooleanField(default=False, verbose_name='Agreed to Terms'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='biometric_enabled',
            field=models.BooleanField(default=False, verbose_name='Biometric Enabled'),
        ),
        migrations.AlterField(
            model_name='user',
            name='clinics',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='auth_vk.clinic', verbose_name='Clinics'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='External ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=128, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Is doctor available for chat', verbose_name='Is Available (for chat)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=128, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='medical_license',
            field=models.CharField(blank=True, help_text='Medical license number for doctors', max_length=100, null=True, verbose_name='Medical License'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(max_length=128, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, help_text="Doctor's specialization", max_length=200, null=True, verbose_name='Specialization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('admin', 'Admin')], default='patient', max_length=10, verbose_name='User Type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='vk_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='VK ID'),
        ),
    ]
