# Generated by Django 5.2 on 2025-08-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_vk', '0027_alter_appointment_options_alter_chatroom_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicimage',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='IntegrationSettings',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.DeleteModel(
            name='OneCSyncLog',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='recommendationfile',
            name='recommendation',
        ),
        migrations.AddField(
            model_name='clinic',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='ClinicImage',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='FeedbackRequest',
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
        migrations.DeleteModel(
            name='RecommendationFile',
        ),
    ]
