# Generated by Django 5.2 on 2025-08-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_vk', '0028_remove_clinicimage_clinic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialzation_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
