# Generated by Django 5.2 on 2025-08-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_vk', '0029_user_specialzation_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Middle Name'),
        ),
    ]
