# Generated by Django 5.2 on 2025-09-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_vk', '0031_alter_appointment_clinic_alter_appointment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_guid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
